apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service
  labels:
    app: balance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-service
  template:
    metadata:
      labels:
        app: balance-service
    spec:
      containers:
      - name: balance-service
        image: 071493677521.dkr.ecr.ap-south-1.amazonaws.com/balance-service:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: balance-service
spec:
  selector:
    app: balance-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  type: LoadBalancer
